In [1]:
import numpy as np
import sympy as sm

## Determinant
### Find Determinant of:

$$\begin{bmatrix} 3&8 \\ 4&6 \end{bmatrix} , \begin{bmatrix} 4&6 \\ 3&8 \end{bmatrix}$$
$$\begin{bmatrix} 6&1&1 \\ 4&-2&5 \\ 2&8&7\end{bmatrix}$$
$$\begin{bmatrix} 3&2&0&1 \\ 4&0&1&2 \\ 3&0&2&1 \\ 9&2&3&1\end{bmatrix}$$


In [2]:

M_1 = np.array([[3, 8],
              [4, 6]])
M_2 = np.array([[4, 6],
                [3, 8]])
M_3 = np.array([[6, 1, 1], 
                [4, -2, 5],
                [2, 8, 7]])
M_4 = np.array([[3, 2, 0, 1],
                [4, 0, 1, 2],
                [3, 0, 2, 1],
                [9, 2, 3, 1]])
print("Matrix 1 ", np.linalg.det(M_1))
print("Matrix 2 ", np.linalg.det(M_2))
print("Matrix 3 ", np.linalg.det(M_3))
print("Matrix 4 ", np.linalg.det(M_4))

Matrix 1  -14.000000000000004
Matrix 2  14.000000000000004
Matrix 3  -306.0
Matrix 4  24.000000000000004


1.  -14.000000000000004
2.  14.000000000000004
3.  -306.0
4.  24.000000000000004


## Matrix Rank
### Find the rank of the matrix (use rref and confirm using matrix_rank())

$$X = \begin{bmatrix} 1&2&4&4 \\ 3&4&8&0 \end{bmatrix}$$
$$Y = \begin{bmatrix} 1&2&3 \\ 2&3&5 \\ 3&4&7 \\ 4&5&9  \end{bmatrix}$$

In [ ]:
X = np.array([  [1, 2, 4, 4],
                [3, 4, 8, 0]])
X_matrix = sm.Matrix(X)

print("Using rref: ", X_matrix.rref())
print("X rank: ", np.linalg.matrix_rank(X))

Using rref:  (Matrix([
[1, 0, 0, -8],
[0, 1, 2,  6]]), (0, 1))
X rank:  2


(Matrix([
[1, 0, 0, -8],
[0, 1, 2,  6]]), (0, 1))

X rank: 2


In [6]:
Y = np.array([  [1, 2, 3], 
                [2, 3, 5],
                [3, 4, 7],
                [4, 5, 9]])

Y_matrix = sm.Matrix(Y)

print("Using rref: ", Y_matrix.rref())
print("Y rank: ", np.linalg.matrix_rank(Y))

Using rref:  (Matrix([
[1, 0, 1],
[0, 1, 1],
[0, 0, 0],
[0, 0, 0]]), (0, 1))
Y rank:  2


(Matrix([
[1, 0, 1],
[0, 1, 1],
[0, 0, 0],
[0, 0, 0]]), (0, 1))

Y rank: 2


## Matrix Inverse
### Find the inverse:

$$\begin{bmatrix} 3&8 \\ 4&6 \end{bmatrix} , \begin{bmatrix} 4&6 \\ 3&8 \end{bmatrix}$$
$$\begin{bmatrix} 6&1&1 \\ 4&-2&5 \\ 2&8&7\end{bmatrix}$$
$$\begin{bmatrix} 3&2&0&1 \\ 4&0&1&2 \\ 3&0&2&1 \\ 9&2&3&1\end{bmatrix}$$

In [8]:
M_1 = np.array([[3, 8],
              [4, 6]])
M_2 = np.array([[4, 6],
                [3, 8]])
M_3 = np.array([[6, 1, 1], 
                [4, -2, 5],
                [2, 8, 7]])
M_4 = np.array([[3, 2, 0, 1],
                [4, 0, 1, 2],
                [3, 0, 2, 1],
                [9, 2, 3, 1]])
print("Matrix 1 \n", np.linalg.inv(M_1))
print("Matrix 2 \n", np.linalg.inv(M_2))
print("Matrix 3 \n", np.linalg.inv(M_3))
print("Matrix 4 \n", np.linalg.inv(M_4))

Matrix 1 
 [[-0.42857143  0.57142857]
 [ 0.28571429 -0.21428571]]
Matrix 2 
 [[ 0.57142857 -0.42857143]
 [-0.21428571  0.28571429]]
Matrix 3 
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]
Matrix 4 
 [[-0.25        0.25       -0.5         0.25      ]
 [ 0.66666667 -0.5         0.5        -0.16666667]
 [ 0.16666667 -0.5         1.         -0.16666667]
 [ 0.41666667  0.25        0.5        -0.41666667]]


1.
 [[-0.42857143  0.57142857]
 [ 0.28571429 -0.21428571]]

2.
 [[ 0.57142857 -0.42857143]
 [-0.21428571  0.28571429]]

3.
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]

4.
 [[-0.25        0.25       -0.5         0.25      ]
 [ 0.66666667 -0.5         0.5        -0.16666667]
 [ 0.16666667 -0.5         1.         -0.16666667]
 [ 0.41666667  0.25        0.5        -0.41666667]]


## Changing Basis (Orthogonal Coordinates)
### Perform the following (Once by dot product and another by matix).
### First confirm b1 and b2 are orthogonal basis.

### 1) Transform $v=\begin{bmatrix}5 \\ -1\end{bmatrix}$ from the stadard basis to b1 and b2 basis. $b_1=\begin{bmatrix}1 \\ 1\end{bmatrix}$ , $b_2=\begin{bmatrix}1\\-1\end{bmatrix}$
### 2) Transform $v=\begin{bmatrix}10\\-5\end{bmatrix}$ from the stadard basis to b1 and b2 basis. $b_1=\begin{bmatrix}3\\ 4\end{bmatrix}$ , $b_2=\begin{bmatrix} 4 \\-3 \end{bmatrix}$

In [19]:
# Ex. 1 Using dot product
b1 = np.array([1, 1])
b2 = np.array([1,-1])
v = np.array([5, -1])

vb1 = (v@b1)/(np.linalg.norm(b1))**2
vb2 = (v@b2)/(np.linalg.norm(b2))**2
vb = np.array([[vb1],
               [vb2]])
print("vb: \n", vb)

vb: 
 [[2.]
 [3.]]


In [ ]:
# Ex. 1 Using dot product


Using dot product
vb:
[[2.]
 [3.]]


In [13]:
# Ex. 1 Using transformation matrix
v = np.array([[5],
              [-1]])
B = np.array([[1, 1],
             [1, -1]])
print(np.linalg.inv(B)@v)

[[2.]
 [3.]]


Using transformation matrix
vb:
[[2.]
 [3.]]


In [20]:
# Ex. 2 Using dot product
b1 = np.array([3, 4])
b2 = np.array([4,-3])
v = np.array([10, -5])

vb1 = (v@b1)/(np.linalg.norm(b1))**2
vb2 = (v@b2)/(np.linalg.norm(b2))**2
vb = np.array([[vb1],
               [vb2]])
print("vb: \n", vb)

vb: 
 [[0.4]
 [2.2]]


Using dot product
vb:
[[0.4]
 [2.2]]


In [21]:
# Ex. 2 Using transformation matrix
v = np.array([[10],
              [-5]])
B = np.array([[3, 4],
             [4, -3]])
print(np.linalg.inv(B)@v)

[[0.4]
 [2.2]]


Using transformation matrix
vb:
[[0.4]
 [2.2]]


## Changing Basis (Non-Orthogonal Coordinates)
### Perform the following.
### First confirm b1 and b2 are non-orthogonal basis.

### - Transform $v=\begin{bmatrix}5 \\ 2\end{bmatrix}$ from the stadard basis to b1 and b2 basis. $b_1=\begin{bmatrix}3 \\ 1\end{bmatrix}$ , $b_2=\begin{bmatrix}1\\1\end{bmatrix}$


In [28]:
B = np.array([[3, 1],
              [1, 1]])
v = np.array([[5], [2]])

print(np.linalg.inv(B)@v)
#NON ORTHOGONALLL

[[1.5]
 [0.5]]


vb:
[[1.5]
 [0.5]]


## Transformation in Non-Orthonormal Space
### - For $R^2$ defined by the basis basis. $b_1=\begin{bmatrix}3 \\ 1\end{bmatrix}$ , $b_2=\begin{bmatrix}1\\1\end{bmatrix}$
### - Find the transformation matrix in B coordinate system for the following transformations:
#### 1- Reflection around x-axis $T=\begin{bmatrix} 1&0 \\ 0&-1\end{bmatrix}$
#### 2- Rotation matrix $T=\begin{bmatrix} 0&1 \\ -1&0\end{bmatrix}$
### - Apply these transformation to the vector  $v_b=\begin{bmatrix}1.5 \\ 0.5\end{bmatrix}$

In [31]:
B = np.array([[3, 1],
              [1, 1]])

B_inv = np.linalg.inv(B)

T_ref = np.array([[1, 0],
              [0, -1]])
T_rot = np.array([[0, 1],
                  [-1, 0]])

T_ref_B = B_inv@T_ref@B
T_rot_B = B_inv@T_rot@B
vb = np.array([[1.5],
               [0.5]])
print("Reflection around x-axis: \n", T_ref_B)
print("Rotation: \n", T_rot_B)
print("Reflection: \n", T_ref_B@vb)
print("Rotation: \n", T_rot_B@vb)

Reflection around x-axis: 
 [[ 2.  1.]
 [-3. -2.]]
Rotation: 
 [[ 2.  1.]
 [-5. -2.]]
Reflection: 
 [[ 3.5]
 [-5.5]]
Rotation: 
 [[ 3.5]
 [-8.5]]


In [ ]:
vb

TB1 =
 [[ 2.  1.]
 [-3. -2.]]

TB2 =
 [[ 2.  1.]
 [-5. -2.]]

vb_TB1 =
 [[ 3.5]
 [-5.5]]

vb_TB2 =
 [[ 3.5]
 [-8.5]]


## Gram–Schmidt Process (Orthogonalization)
### Apply Gram-Shmidt process for the following sequence in vectors in $R^3$:
### $$\begin{bmatrix}1 \\2\\ 0\end{bmatrix} , \begin{bmatrix}8 \\1\\ -6\end{bmatrix} , \begin{bmatrix}0 \\0\\ 1\end{bmatrix}$$
#### Confirm your answer using numpy.linalg.qr() function
#### Make sure all vectors given above are basis in $R^3$ space.
#### Confirm that the orthogonal matrix has orthonormal vectors.
#### Confirm that the transpose of the orthogonal matrix is it's inverse.
#### Reflect the vector r = (1,3,4) arround the xy plane containing the two vectors $\begin{bmatrix}1 \\2\\ 0\end{bmatrix} , \begin{bmatrix}8 \\1\\ -6\end{bmatrix}$.
#### Round all results to 3 decimal points.

In [32]:
M = np.array([[1, 8, 0],
              [2, 1, 0],
              [0, -6, 1]])
M_sm = sm.Matrix(M)
print("det(M): ", np.linalg.det(M))
print("Mrref: ", M_sm.rref())

det(M):  -15.0
Mrref:  (Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]]), (0, 1, 2))


det(V): -15.0
Mrref:
 (Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]]), (0, 1, 2))


In [42]:
a = np.array([1, 2, 0])
b = np.array([8, 1, -6])
c = np.array([0, 0, 1])

v1 = a
v2 = b - ((np.dot(b, v1))/np.dot(v1, v1))*v1
v3 = c - ((np.dot(c, v1))/np.dot(v1, v1))*v1 - (np.dot(c, v2)/np.dot(v2, v2))*v2

q1 = v1/ np.linalg.norm(v1)
q2 = v2/ np.linalg.norm(v2)
q3 = v3/ np.linalg.norm(v3)

print("v1: \n", v1.reshape(-1,1))
print("v2: \n", v2.reshape(-1,1))
print("v3: \n", v3.reshape(-1,1))
print("q1: \n", q1.reshape(-1,1))
print("q2: \n", q2.reshape(-1,1))
print("q3: \n", q3.reshape(-1,1))

v1: 
 [[1]
 [2]
 [0]]
v2: 
 [[ 6.]
 [-3.]
 [-6.]]
v3: 
 [[ 0.44444444]
 [-0.22222222]
 [ 0.55555556]]
q1: 
 [[0.4472136 ]
 [0.89442719]
 [0.        ]]
q2: 
 [[ 0.66666667]
 [-0.33333333]
 [-0.66666667]]
q3: 
 [[ 0.59628479]
 [-0.2981424 ]
 [ 0.74535599]]


u1:
[[1]
 [2]
 [0]]

u2:
[[ 6.]
 [-3.]
 [-6.]]

u3:
[[ 0.44444444]
 [-0.22222222]
 [ 0.55555556]]

e1:
[[0.4472136 ]
 [0.89442719]
 [0.        ]]

e2:
[[ 0.66666667]
 [-0.33333333]
 [-0.66666667]]

e3:
[[ 0.59628479]
 [-0.2981424 ]
 [ 0.74535599]]


In [47]:
Q, R = np.linalg.qr(M)
print("Using QR: \n", Q)

Using QR: 
 [[-0.4472136   0.66666667  0.59628479]
 [-0.89442719 -0.33333333 -0.2981424 ]
 [-0.         -0.66666667  0.74535599]]


Using QR:
[[-0.4472136   0.66666667  0.59628479]
 [-0.89442719 -0.33333333 -0.2981424 ]
 [-0.         -0.66666667  0.74535599]]


In [50]:
print(np.linalg.norm(q1))
print(np.linalg.norm(q2))
print(np.linalg.norm(q3))

0.9999999999999999
1.0
1.0


1.0

In [53]:
Q_inv = np.linalg.inv(Q)
Q_transpose = Q.T
print("Q inverse: \n", np.round(Q_inv, 3))
print("Q Transpose: \n",  np.round(Q_transpose, 3))

Q inverse: 
 [[-0.447 -0.894 -0.   ]
 [ 0.667 -0.333 -0.667]
 [ 0.596 -0.298  0.745]]
Q Transpose: 
 [[-0.447 -0.894 -0.   ]
 [ 0.667 -0.333 -0.667]
 [ 0.596 -0.298  0.745]]


Q Inverse:
 [[-0.447 -0.894 -0.   ]
 [ 0.667 -0.333 -0.667]
 [ 0.596 -0.298  0.745]]
Q Transpose
 [[-0.447 -0.894 -0.   ]
 [ 0.667 -0.333 -0.667]
 [ 0.596 -0.298  0.745]]


In [ ]:
r = np.array([1, 3, 4])
T = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, -1]])
T_B = Q@T@Q_inv
print("Transformation matrix in the non-orthonormal basis: \n", T_B)
print("Transformed vector: \n", T_B@r.reshape(-1,1))

Transformation matrix in the non-orthonormal basis: 
 [[ 0.28888889  0.35555556 -0.88888889]
 [ 0.35555556  0.82222222  0.44444444]
 [-0.88888889  0.44444444 -0.11111111]]
Transformed vector: 
 [[-2.2]
 [ 4.6]
 [ 0. ]]


: 

Transformation matrix in the non-orthonormal basis:
[[ 0.28888889  0.35555556 -0.88888889]
 [ 0.35555556  0.82222222  0.44444444]
 [-0.88888889  0.44444444 -0.11111111]]

Transformed vector:
[[-2.2]
 [ 4.6]
 [ 0. ]]
