In [1]:
import numpy as np
import sympy as sm

## Determinant
### Find Determinant of:

$$\begin{bmatrix} 3&8 \\ 4&6 \end{bmatrix} , \begin{bmatrix} 4&6 \\ 3&8 \end{bmatrix}$$
$$\begin{bmatrix} 6&1&1 \\ 4&-2&5 \\ 2&8&7\end{bmatrix}$$
$$\begin{bmatrix} 3&2&0&1 \\ 4&0&1&2 \\ 3&0&2&1 \\ 9&2&3&1\end{bmatrix}$$


In [2]:
A1 = np.array([[3,8],
               [4,6]])
A2 = np.array([[4,6],
               [3,8]])
A3 = np.array([[6,1,1],
               [4,-2,5],
               [2,8,7]])
A4 = np.array([[3,2,0,1],
               [4,0,1,2],
               [3,0,2,1],
               [9,2,3,1]])

A1_d = np.linalg.det(A1)
A2_d = np.linalg.det(A2)
A3_d = np.linalg.det(A3)
A4_d = np.linalg.det(A4)
print(A1_d,A2_d,A3_d,A4_d)







-14.000000000000004 14.000000000000004 -306.0 24.000000000000004


1.  -14.000000000000004
2.  14.000000000000004
3.  -306.0
4.  24.000000000000004


## Matrix Rank
### Find the rank of the matrix (use rref and confirm using matrix_rank())

$$X = \begin{bmatrix} 1&2&4&4 \\ 3&4&8&0 \end{bmatrix}$$
$$Y = \begin{bmatrix} 1&2&3 \\ 2&3&5 \\ 3&4&7 \\ 4&5&9  \end{bmatrix}$$

In [3]:
X = np.array([[1,2,4,4],
              [3,4,8,0]])

X_new = sm.Matrix(X)
print(X_new.rref())
print(np.linalg.matrix_rank(X))


(Matrix([
[1, 0, 0, -8],
[0, 1, 2,  6]]), (0, 1))
2


(Matrix([
[1, 0, 0, -8],
[0, 1, 2,  6]]), (0, 1))

X rank: 2


In [4]:
X = np.array([[1,2,3],
              [2,3,5],
              [3,4,7],
              [4,5,9]])

X_new = sm.Matrix(X)
print(X_new.rref())
print(np.linalg.matrix_rank(X))


(Matrix([
[1, 0, 1],
[0, 1, 1],
[0, 0, 0],
[0, 0, 0]]), (0, 1))
2


(Matrix([
[1, 0, 1],
[0, 1, 1],
[0, 0, 0],
[0, 0, 0]]), (0, 1))

Y rank: 2


## Matrix Inverse
### Find the inverse:

$$\begin{bmatrix} 3&8 \\ 4&6 \end{bmatrix} , \begin{bmatrix} 4&6 \\ 3&8 \end{bmatrix}$$
$$\begin{bmatrix} 6&1&1 \\ 4&-2&5 \\ 2&8&7\end{bmatrix}$$
$$\begin{bmatrix} 3&2&0&1 \\ 4&0&1&2 \\ 3&0&2&1 \\ 9&2&3&1\end{bmatrix}$$

In [6]:
A1 = np.array([[3,8],
               [4,6]])
A2 = np.array([[4,6],
               [3,8]])
A3 = np.array([[6,1,1],
               [4,-2,5],
               [2,8,7]])
A4 = np.array([[3,2,0,1],
               [4,0,1,2],
               [3,0,2,1],
               [9,2,3,1]])

A1_i = np.linalg.inv(A1)
A2_i = np.linalg.inv(A2)
A3_i = np.linalg.inv(A3)
A4_i = np.linalg.inv(A4)
print(A1_i,'\n',A2_i,'\n',A3_i,'\n',A4_i)

[[-0.42857143  0.57142857]
 [ 0.28571429 -0.21428571]] 
 [[ 0.57142857 -0.42857143]
 [-0.21428571  0.28571429]] 
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]] 
 [[-0.25        0.25       -0.5         0.25      ]
 [ 0.66666667 -0.5         0.5        -0.16666667]
 [ 0.16666667 -0.5         1.         -0.16666667]
 [ 0.41666667  0.25        0.5        -0.41666667]]


1.
 [[-0.42857143  0.57142857]
 [ 0.28571429 -0.21428571]]

2.
 [[ 0.57142857 -0.42857143]
 [-0.21428571  0.28571429]]

3.
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]

4.
 [[-0.25        0.25       -0.5         0.25      ]
 [ 0.66666667 -0.5         0.5        -0.16666667]
 [ 0.16666667 -0.5         1.         -0.16666667]
 [ 0.41666667  0.25        0.5        -0.41666667]]


## Changing Basis (Orthogonal Coordinates)
### Perform the following (Once by dot product and another by matix).
### First confirm b1 and b2 are orthogonal basis.

### 1) Transform $v=\begin{bmatrix}5 \\ -1\end{bmatrix}$ from the stadard basis to b1 and b2 basis. $b_1=\begin{bmatrix}1 \\ 1\end{bmatrix}$ , $b_2=\begin{bmatrix}1\\-1\end{bmatrix}$
### 2) Transform $v=\begin{bmatrix}10\\-5\end{bmatrix}$ from the stadard basis to b1 and b2 basis. $b_1=\begin{bmatrix}3\\ 4\end{bmatrix}$ , $b_2=\begin{bmatrix} 4 \\-3 \end{bmatrix}$

In [16]:
v = np.array([5,
              -1])
b1 = np.array([1,
            1])
b2 = np.array([1,
            -1])
vb1 = (v@b1)/(np.linalg.norm(b1))**2
vb2 = (v@b2)/(np.linalg.norm(b2))**2
vb = np.array([[vb1],
               [vb2]])
print(vb)


[[2.]
 [3.]]


In [7]:
# Ex. 1 Using dot product


[[2.]
 [3.]]


In [9]:
v = np.array([[5],
              [-1]])
b = np.array([[1, 1],
               [1,-1]])
b_inv = np.linalg.inv(b)
print(b_inv@v)

[[2.]
 [3.]]


In [17]:
v = np.array([10,
              -5])
b1 = np.array([3,
            4])
b2 = np.array([4,
            -3])
vb1 = (v@b1)/(np.linalg.norm(b1))**2
vb2 = (v@b2)/(np.linalg.norm(b2))**2
vb = np.array([[vb1],
               [vb2]])
print(vb)


[[0.4]
 [2.2]]


In [18]:
v = np.array([[10],
              [-5]])
b = np.array([[3, 4],
               [4,-3]])
b_inv = np.linalg.inv(b)
print(b_inv@v)

[[0.4]
 [2.2]]


In [ ]:
# Ex. 1 Using transformation matrix


Using transformation matrix
vb:
[[2.]
 [3.]]


In [ ]:
# Ex. 2 Using dot product


Using dot product
vb:
[[0.4]
 [2.2]]


In [ ]:
# Ex. 2 Using transformation matrix


Using transformation matrix
vb:
[[0.4]
 [2.2]]


## Changing Basis (Non-Orthogonal Coordinates)
### Perform the following.
### First confirm b1 and b2 are non-orthogonal basis.

### - Transform $v=\begin{bmatrix}5 \\ 2\end{bmatrix}$ from the stadard basis to b1 and b2 basis. $b_1=\begin{bmatrix}3 \\ 1\end{bmatrix}$ , $b_2=\begin{bmatrix}1\\1\end{bmatrix}$


In [30]:
b1 = np.array([3,
               1])
b2 = np.array([1,
               1])
print(b1@b2)

b = np.array([[3,1],
              [1,1]])
v = np.array([[5],
              [2]])
print(np.linalg.inv(b)@v)

4
[[1.5]
 [0.5]]


vb:
[[1.5]
 [0.5]]


## Transformation in Non-Orthonormal Space
### - For $R^2$ defined by the basis basis. $b_1=\begin{bmatrix}3 \\ 1\end{bmatrix}$ , $b_2=\begin{bmatrix}1\\1\end{bmatrix}$
### - Find the transformation matrix in B coordinate system for the following transformations:
#### 1- Reflection around x-axis $T=\begin{bmatrix} 1&0 \\ 0&-1\end{bmatrix}$
#### 2- Rotation matrix $T=\begin{bmatrix} 0&1 \\ -1&0\end{bmatrix}$
### - Apply these transformation to the vector  $v_b=\begin{bmatrix}1.5 \\ 0.5\end{bmatrix}$

In [37]:
b = np.array([[3,1],
              [1,1]])
T = np.array([[1,0],
              [0,-1]])
b_inv = np.linalg.inv(b)
T_new = b_inv@T@b
print(T_new)
################################
T2 = np.array([[0,1],
              [-1,0]])
T_new2 = b_inv@T2@b
print(T_new2)

####################################
vb = np.array([[1.5],
               [0.5]])

Tvb1 = T_new@vb
Tvb2 = T_new2@vb

print(Tvb1)
print(Tvb2)


[[ 2.  1.]
 [-3. -2.]]
[[ 2.  1.]
 [-5. -2.]]
[[ 3.5]
 [-5.5]]
[[ 3.5]
 [-8.5]]


TB1 =
 [[ 2.  1.]
 [-3. -2.]]

TB2 =
 [[ 2.  1.]
 [-5. -2.]]

vb_TB1 =
 [[ 3.5]
 [-5.5]]

vb_TB2 =
 [[ 3.5]
 [-8.5]]


## Gram–Schmidt Process (Orthogonalization)
### Apply Gram-Shmidt process for the following sequence in vectors in $R^3$:
### $$\begin{bmatrix}1 \\2\\ 0\end{bmatrix} , \begin{bmatrix}8 \\1\\ -6\end{bmatrix} , \begin{bmatrix}0 \\0\\ 1\end{bmatrix}$$
#### Confirm your answer using numpy.linalg.qr() function
#### Make sure all vectors given above are basis in $R^3$ space.
#### Confirm that the orthogonal matrix has orthonormal vectors.
#### Confirm that the transpose of the orthogonal matrix is it's inverse.
#### Reflect the vector r = (1,3,4) arround the xy plane containing the two vectors $\begin{bmatrix}1 \\2\\ 0\end{bmatrix} , \begin{bmatrix}8 \\1\\ -6\end{bmatrix}$.
#### Round all results to 3 decimal points.

In [38]:
g = np.array([[1,8,0],
              [2,1,0],
              [0,-6,1]])

print(np.linalg.det(g))
M = sm.Matrix(g)
print(M.rref())

-15.0
(Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]]), (0, 1, 2))


det(V): -15.0
Mrref:
 (Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]]), (0, 1, 2))


In [52]:
a = np.array([1,
               2,
               0])
b = np.array([8,
              1,
              -6])
c = np.array([0,
               0,
               1])
u1 = a
u2 = b - (((b@u1)/(u1@u1)))*u1
u3 = c - ((c@u1)/(u1@u1))*u1 - ((c@u2)/(u2@u2))*u2
print(u1.reshape(-1,1))
print(u2.reshape(-1,1))
print(u3.reshape(-1,1))
# ORTHONORMAL
e1 = u1/np.linalg.norm(u1)
e2 = u2/np.linalg.norm(u2)
e3 = u3/np.linalg.norm(u3)
print(e1.reshape(-1,1))
print(e2.reshape(-1,1))
print(e3.reshape(-1,1))


[[1]
 [2]
 [0]]
[[ 6.]
 [-3.]
 [-6.]]
[[ 0.44444444]
 [-0.22222222]
 [ 0.55555556]]
[[0.4472136 ]
 [0.89442719]
 [0.        ]]
[[ 0.66666667]
 [-0.33333333]
 [-0.66666667]]
[[ 0.59628479]
 [-0.2981424 ]
 [ 0.74535599]]


u1:
[[1]
 [2]
 [0]]

u2:
[[ 6.]
 [-3.]
 [-6.]]

u3:
[[ 0.44444444]
 [-0.22222222]
 [ 0.55555556]]

e1:
[[0.4472136 ]
 [0.89442719]
 [0.        ]]

e2:
[[ 0.66666667]
 [-0.33333333]
 [-0.66666667]]

e3:
[[ 0.59628479]
 [-0.2981424 ]
 [ 0.74535599]]


In [53]:
Q, R = np.linalg.qr(g)
print(Q)

[[-0.4472136   0.66666667  0.59628479]
 [-0.89442719 -0.33333333 -0.2981424 ]
 [-0.         -0.66666667  0.74535599]]


Using QR:
[[-0.4472136   0.66666667  0.59628479]
 [-0.89442719 -0.33333333 -0.2981424 ]
 [-0.         -0.66666667  0.74535599]]


In [54]:
#INVERSES OF ORTHORNORMAL
print(np.linalg.norm(e1))
print(np.linalg.norm(e2))
print(np.linalg.norm(e3))


0.9999999999999999
1.0
1.0


1.0

In [60]:
Q_inv = np.linalg.inv(Q)
print(Q_inv)
print(np.transpose(Q))

[[-4.47213595e-01 -8.94427191e-01 -9.30950307e-17]
 [ 6.66666667e-01 -3.33333333e-01 -6.66666667e-01]
 [ 5.96284794e-01 -2.98142397e-01  7.45355992e-01]]
[[-0.4472136  -0.89442719 -0.        ]
 [ 0.66666667 -0.33333333 -0.66666667]
 [ 0.59628479 -0.2981424   0.74535599]]


Q Inverse:
 [[-0.447 -0.894 -0.   ]
 [ 0.667 -0.333 -0.667]
 [ 0.596 -0.298  0.745]]
Q Transpose
 [[-0.447 -0.894 -0.   ]
 [ 0.667 -0.333 -0.667]
 [ 0.596 -0.298  0.745]]


In [65]:
b = np.array([1,
              3,
              4])
T = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, -1]])
T_new = Q@T@Q_inv
print(T_new)
print(T_new@b.reshape(-1,1))


[[ 0.28888889  0.35555556 -0.88888889]
 [ 0.35555556  0.82222222  0.44444444]
 [-0.88888889  0.44444444 -0.11111111]]
[[-2.2]
 [ 4.6]
 [ 0. ]]


Transformation matrix in the non-orthonormal basis:
[[ 0.28888889  0.35555556 -0.88888889]
 [ 0.35555556  0.82222222  0.44444444]
 [-0.88888889  0.44444444 -0.11111111]]

Transformed vector:
[[-2.2]
 [ 4.6]
 [ 0. ]]
